/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTicketsRouteImport } from './routes/dashboard.tickets'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as DashboardEquipementsIndexRouteImport } from './routes/dashboard.equipements.index'
import { Route as DashboardContratsIndexRouteImport } from './routes/dashboard.contrats.index'
import { Route as DashboardClientsIndexRouteImport } from './routes/dashboard.clients.index'
import { Route as DashboardEquipementsRefRouteImport } from './routes/dashboard.equipements.$ref'
import { Route as DashboardContratsClientIdRouteImport } from './routes/dashboard.contrats.$clientId'
import { Route as DashboardClientsSlugRouteImport } from './routes/dashboard.clients.$slug'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTicketsRoute = DashboardTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => DashboardRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardEquipementsIndexRoute =
  DashboardEquipementsIndexRouteImport.update({
    id: '/equipements/',
    path: '/equipements/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardContratsIndexRoute = DashboardContratsIndexRouteImport.update({
  id: '/contrats/',
  path: '/contrats/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsIndexRoute = DashboardClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEquipementsRefRoute = DashboardEquipementsRefRouteImport.update({
  id: '/equipements/$ref',
  path: '/equipements/$ref',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContratsClientIdRoute =
  DashboardContratsClientIdRouteImport.update({
    id: '/contrats/$clientId',
    path: '/contrats/$clientId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardClientsSlugRoute = DashboardClientsSlugRouteImport.update({
  id: '/clients/$slug',
  path: '/clients/$slug',
  getParentRoute: () => DashboardRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/signup': typeof SignupRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/dashboard/clients/$slug': typeof DashboardClientsSlugRoute
  '/dashboard/contrats/$clientId': typeof DashboardContratsClientIdRoute
  '/dashboard/equipements/$ref': typeof DashboardEquipementsRefRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
  '/dashboard/contrats/': typeof DashboardContratsIndexRoute
  '/dashboard/equipements/': typeof DashboardEquipementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/signup': typeof SignupRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/dashboard/clients/$slug': typeof DashboardClientsSlugRoute
  '/dashboard/contrats/$clientId': typeof DashboardContratsClientIdRoute
  '/dashboard/equipements/$ref': typeof DashboardEquipementsRefRoute
  '/dashboard/clients': typeof DashboardClientsIndexRoute
  '/dashboard/contrats': typeof DashboardContratsIndexRoute
  '/dashboard/equipements': typeof DashboardEquipementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/signup': typeof SignupRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/dashboard/clients/$slug': typeof DashboardClientsSlugRoute
  '/dashboard/contrats/$clientId': typeof DashboardContratsClientIdRoute
  '/dashboard/equipements/$ref': typeof DashboardEquipementsRefRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
  '/dashboard/contrats/': typeof DashboardContratsIndexRoute
  '/dashboard/equipements/': typeof DashboardEquipementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/mcp'
    | '/signup'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard/tickets'
    | '/dashboard/'
    | '/.mcp/invoke-tool/$tool'
    | '/dashboard/clients/$slug'
    | '/dashboard/contrats/$clientId'
    | '/dashboard/equipements/$ref'
    | '/dashboard/clients/'
    | '/dashboard/contrats/'
    | '/dashboard/equipements/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mcp'
    | '/signup'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard/tickets'
    | '/dashboard'
    | '/.mcp/invoke-tool/$tool'
    | '/dashboard/clients/$slug'
    | '/dashboard/contrats/$clientId'
    | '/dashboard/equipements/$ref'
    | '/dashboard/clients'
    | '/dashboard/contrats'
    | '/dashboard/equipements'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/mcp'
    | '/signup'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard/tickets'
    | '/dashboard/'
    | '/.mcp/invoke-tool/$tool'
    | '/dashboard/clients/$slug'
    | '/dashboard/contrats/$clientId'
    | '/dashboard/equipements/$ref'
    | '/dashboard/clients/'
    | '/dashboard/contrats/'
    | '/dashboard/equipements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  SignupRoute: typeof SignupRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tickets': {
      id: '/dashboard/tickets'
      path: '/tickets'
      fullPath: '/dashboard/tickets'
      preLoaderRoute: typeof DashboardTicketsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/equipements/': {
      id: '/dashboard/equipements/'
      path: '/equipements'
      fullPath: '/dashboard/equipements/'
      preLoaderRoute: typeof DashboardEquipementsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contrats/': {
      id: '/dashboard/contrats/'
      path: '/contrats'
      fullPath: '/dashboard/contrats/'
      preLoaderRoute: typeof DashboardContratsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients/': {
      id: '/dashboard/clients/'
      path: '/clients'
      fullPath: '/dashboard/clients/'
      preLoaderRoute: typeof DashboardClientsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/equipements/$ref': {
      id: '/dashboard/equipements/$ref'
      path: '/equipements/$ref'
      fullPath: '/dashboard/equipements/$ref'
      preLoaderRoute: typeof DashboardEquipementsRefRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contrats/$clientId': {
      id: '/dashboard/contrats/$clientId'
      path: '/contrats/$clientId'
      fullPath: '/dashboard/contrats/$clientId'
      preLoaderRoute: typeof DashboardContratsClientIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients/$slug': {
      id: '/dashboard/clients/$slug'
      path: '/clients/$slug'
      fullPath: '/dashboard/clients/$slug'
      preLoaderRoute: typeof DashboardClientsSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardTicketsRoute: typeof DashboardTicketsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardClientsSlugRoute: typeof DashboardClientsSlugRoute
  DashboardContratsClientIdRoute: typeof DashboardContratsClientIdRoute
  DashboardEquipementsRefRoute: typeof DashboardEquipementsRefRoute
  DashboardClientsIndexRoute: typeof DashboardClientsIndexRoute
  DashboardContratsIndexRoute: typeof DashboardContratsIndexRoute
  DashboardEquipementsIndexRoute: typeof DashboardEquipementsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardTicketsRoute: DashboardTicketsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardClientsSlugRoute: DashboardClientsSlugRoute,
  DashboardContratsClientIdRoute: DashboardContratsClientIdRoute,
  DashboardEquipementsRefRoute: DashboardEquipementsRefRoute,
  DashboardClientsIndexRoute: DashboardClientsIndexRoute,
  DashboardContratsIndexRoute: DashboardContratsIndexRoute,
  DashboardEquipementsIndexRoute: DashboardEquipementsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  SignupRoute: SignupRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
