/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTicketsRouteImport } from './routes/dashboard.tickets'
import { Route as DashboardEquipementsRouteImport } from './routes/dashboard.equipements'
import { Route as DashboardContratsRouteImport } from './routes/dashboard.contrats'
import { Route as DashboardClientsIndexRouteImport } from './routes/dashboard.clients.index'
import { Route as DashboardClientsSlugRouteImport } from './routes/dashboard.clients.$slug'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTicketsRoute = DashboardTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEquipementsRoute = DashboardEquipementsRouteImport.update({
  id: '/equipements',
  path: '/equipements',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContratsRoute = DashboardContratsRouteImport.update({
  id: '/contrats',
  path: '/contrats',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsIndexRoute = DashboardClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsSlugRoute = DashboardClientsSlugRouteImport.update({
  id: '/clients/$slug',
  path: '/clients/$slug',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/contrats': typeof DashboardContratsRoute
  '/dashboard/equipements': typeof DashboardEquipementsRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/clients/$slug': typeof DashboardClientsSlugRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/contrats': typeof DashboardContratsRoute
  '/dashboard/equipements': typeof DashboardEquipementsRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/clients/$slug': typeof DashboardClientsSlugRoute
  '/dashboard/clients': typeof DashboardClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/contrats': typeof DashboardContratsRoute
  '/dashboard/equipements': typeof DashboardEquipementsRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/clients/$slug': typeof DashboardClientsSlugRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/contrats'
    | '/dashboard/equipements'
    | '/dashboard/tickets'
    | '/dashboard/'
    | '/dashboard/clients/$slug'
    | '/dashboard/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/contrats'
    | '/dashboard/equipements'
    | '/dashboard/tickets'
    | '/dashboard'
    | '/dashboard/clients/$slug'
    | '/dashboard/clients'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/contrats'
    | '/dashboard/equipements'
    | '/dashboard/tickets'
    | '/dashboard/'
    | '/dashboard/clients/$slug'
    | '/dashboard/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tickets': {
      id: '/dashboard/tickets'
      path: '/tickets'
      fullPath: '/dashboard/tickets'
      preLoaderRoute: typeof DashboardTicketsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/equipements': {
      id: '/dashboard/equipements'
      path: '/equipements'
      fullPath: '/dashboard/equipements'
      preLoaderRoute: typeof DashboardEquipementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contrats': {
      id: '/dashboard/contrats'
      path: '/contrats'
      fullPath: '/dashboard/contrats'
      preLoaderRoute: typeof DashboardContratsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients/': {
      id: '/dashboard/clients/'
      path: '/clients'
      fullPath: '/dashboard/clients/'
      preLoaderRoute: typeof DashboardClientsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients/$slug': {
      id: '/dashboard/clients/$slug'
      path: '/clients/$slug'
      fullPath: '/dashboard/clients/$slug'
      preLoaderRoute: typeof DashboardClientsSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardContratsRoute: typeof DashboardContratsRoute
  DashboardEquipementsRoute: typeof DashboardEquipementsRoute
  DashboardTicketsRoute: typeof DashboardTicketsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardClientsSlugRoute: typeof DashboardClientsSlugRoute
  DashboardClientsIndexRoute: typeof DashboardClientsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardContratsRoute: DashboardContratsRoute,
  DashboardEquipementsRoute: DashboardEquipementsRoute,
  DashboardTicketsRoute: DashboardTicketsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardClientsSlugRoute: DashboardClientsSlugRoute,
  DashboardClientsIndexRoute: DashboardClientsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
